---
- name: Create the data capsule hosting user
  become: true
  user:
    name: '{{ HOST_USERNAME }}'
    password: "{{ HOST_USER_PASSWORD | password_hash('sha512') }}"
    update_password: on_create

- name: Add the data capsule hosting user to the sudoers
  become: true
  lineinfile:
    path: /etc/sudoers
    state: present
    regexp: "^{{ HOST_USERNAME }}"
    line: "{{ HOST_USERNAME }}  ALL=(ALL) NOPASSWD: {{ SCRIPT_DIR }}/sshfwd.sh, NOPASSWD: {{ SCRIPT_DIR }}/fw.sh, NOPASSWD: {{ SCRIPT_DIR }}/launchkvm.sh, NOPASSWD: {{ SCRIPT_DIR }}/remove-vm-iptables.sh, NOPASSWD: /bin/mount, NOPASSWD: /bin/umount"
    validate: 'visudo -cf %s'
